sudo: required
dist: trusty

language: node_js
node_js:
  - 4.4

cache:
   directories:
     - node_modules
     - bower_components

install:
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  - sudo apt-get update -q
  - sudo apt-get install -q google-chrome-stable

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - webdriver-manager update
  - npm install -g bower
  - npm install -g gulp
  - bower install
  - gulp > /dev/null & # start server
  - sleep 10 # give server time to start

after_success:
#  - mv coverage/cobertura-coverage.xml shippable/codecoverage/coverage.xml
#  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js --verbose
#  - cat ./coverage/lcov.info | codeclimate
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN codeclimate-test-reporter < ./coverage/**/lcov.info


#deploy:
#  provider: npm
#  email: paul.gualotuna@tum.de
#  api_key: $NPM_API_KEY
#  on:
#    tags: true
#    all_branches: true
#    node: '0.12' # this should be quoted; otherwise, 0.10 would not work
#    repo: poulzinho/pokemap_1
